### ISSUE TITLE
قالب پروژه

### ISSUE THREAD

**Issue by alirezaseif28** [VahidN/AngularMaterialLab#1]
سلام
سوالی داشتم از خدمتتون.
برای ساخت یک سایت با
asp.netcore  و angular
من دو روش در سایت شما دیدم.
یکی اینکه تمامی فایل های 
asp.netcore و angular
با هم در یک پوشه قرار دارند.
و دومی شبیه این ریپازیتوری شما.
که بخش 
asp.netcore و  angular
جدا کردید.
کدام روش را پیشنهاد می کنید؟
مرسی

**Comment by VahidN** [comment]
[روش دوم](https://www.dotnettips.info/post/2658)

**Comment by alirezaseif28** [comment]
مرسی. این لینک که قرار دادید به نظرم که پیاده سازی کردم مثل این ریپازیتوری نمیشه.درسته؟
